UBUNTU: SAUCE: selftests/seccomp fix compilation issue for amd64
BugLink: https://bugs.launchpad.net/bugs/2154174

ubuntu_kernel_selftests:seccomp_build test fails for amd64 due to compilation
issues:

seccomp_bpf.c: In function ‘UPROBE_setup’:
seccomp_bpf.c:5175:74: error: pointer type mismatch in conditional expression [-Wincompatible-pointer-types]
5175 | offset = get_uprobe_offset(variant->uretprobe ? probed_uretprobe : probed_uprobe);
| ^
seccomp_bpf.c:5175:57: note: first expression has type ‘int (*)(void)’
5175 | offset = get_uprobe_offset(variant->uretprobe ? probed_uretprobe : probed_uprobe);
| ^~~~~~~~~~~~~~~~
seccomp_bpf.c:5175:76: note: second expression has type ‘int (__attribute__((nocf_check)) *)(void)’
5175 | offset = get_uprobe_offset(variant->uretprobe ? probed_uretprobe : probed_uprobe);
| ^~~~~~~~~~~~~

get_uprobe_offset() implicity casts functions pointers to (void *), make
it explicit to resolve the issue.

Signed-off-by: Mehmet Basaran <mehmet.basaran@canonical.com>
Acked-by: Edoardo Canepa <edoardo.canepa@canonical.com>
Signed-off-by: Timo Aaltonen <timo.aaltonen@canonical.com>